In [31]:
import numpy as np 

docs = ['go india',
        'india india',
        'hip hip hurray',
        'jeetega bhai jeetega india jeetega',
        'bharat mata ki jai',
        'kohli kohli',
        'sachin sachin',
        'dhoni dhoni',
        'anjali ji ki jai',
        'inquilab zindabad']

In [32]:
import tensorflow
from tensorflow import keras
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.layers import Dense,SimpleRNN,Embedding,Flatten
from keras import Sequential

In [33]:
tokenizer =Tokenizer()
tokenizer.fit_on_texts(docs)

In [34]:
len(tokenizer.word_index)

17

In [35]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [36]:
from keras.utils import pad_sequences

In [37]:
sequences = pad_sequences(sequences,padding='post')
sequences


array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [38]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten,Input

In [39]:
model = Sequential()
vocab_size = len(tokenizer.word_index) + 1
model.add(Input(shape=(5,)))
model.add(Embedding(vocab_size,output_dim=2))
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 5, 2)           │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 36 (144.00 B)

 Trainable params: 36 (144.00 B)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.compile('adam','accuracy')

In [41]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
[[[ 0.03812357  0.02924577]
  [ 0.03257802  0.01584569]
  [ 0.00195718  0.01548066]
  [ 0.00195718  0.01548066]
  [ 0.00195718  0.01548066]]

 [[ 0.03257802  0.01584569]
  [ 0.03257802  0.01584569]
  [ 0.00195718  0.01548066]
  [ 0.00195718  0.01548066]
  [ 0.00195718  0.01548066]]

 [[ 0.02496401 -0.00349507]
  [ 0.02496401 -0.00349507]
  [ 0.04233146 -0.02394798]
  [ 0.00195718  0.01548066]
  [ 0.00195718  0.01548066]]

 [[-0.01791121 -0.04794811]
  [-0.04845376 -0.00176939]
  [-0.01791121 -0.04794811]
  [ 0.03257802  0.01584569]
  [-0.01791121 -0.04794811]]

 [[ 0.02136724  0.04791755]
  [ 0.02638802  0.04656233]
  [-0.01750116  0.03135953]
  [ 0.01369094 -0.00681852]
  [ 0.00195718  0.01548066]]

 [[ 0.03240696 -0.02961205]
  [ 0.03240696 -0.02961205]
  [ 0.00195718  0.01548066]
  [ 0.00195718  0.01548066]
  [ 0.00195718  0.01548066]]

 [[-0.04200089  0.03313481]
  [-0.04200089  0.03313481]
  [ 0.00195718  0.01548066]
  [ 0.00195718  0.01548066

In [55]:
(X_train,y_train),(X_test,y_test) = imdb.load_data(num_words=10000)

In [56]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [57]:
X_train.shape

(25000, 50)

In [58]:
model1 = Sequential()
model1.add(Input(shape=(50,)))
model1.add(Embedding(10000,2))
model1.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False))
model1.add(Dense(1,activation='sigmoid'))

model1.summary()

c:\Users\anjal\.conda\envs\myenv\lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_10 (Embedding)        │ (None, 50, 2)          │        20,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_7 (SimpleRNN)        │ (None, 32)             │         1,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [59]:
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])


In [60]:
history = model1.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5


782/782 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.6348 - loss: 0.6028 - val_accuracy: 0.7978 - val_loss: 0.4410
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8268 - loss: 0.3945 - val_accuracy: 0.8115 - val_loss: 0.4198
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8648 - loss: 0.3275 - val_accuracy: 0.8056 - val_loss: 0.4574
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8858 - loss: 0.2859 - val_accuracy: 0.8031 - val_loss: 0.4430
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8988 - loss: 0.2584 - val_accuracy: 0.8006 - val_loss: 0.4644
